### ISSUE TITLE
Why does the UMAT not use `real(wp)`?

### ISSUE THREAD

**Issue by Spectre5** [BristolCompositesInstitute/abaqus-modern-fortran#2]
In `umat.f`, the abaqus "kind" is in use by the statement `use Abaqus_Definitions, only: wp=>abaqus_real_kind` and this abaqus definition is the whole point of this example repository.  But why then do the variables all use `real(dp)` instead of `real(wp)`?  For example:
```
real(dp), intent(inout) :: stress(ntens), statev(nstatv), ddsdde(ntens,ntens)
```

**Comment by LKedward** [comment]
Thanks for reporting - looks like a copy-paste error. Please feel free to open a pull request to correct if you have the time :)
